### ISSUE TITLE
UInt64.lt Bug

### ISSUE THREAD

**Issue by frisitano** [o1-labs/snarkyjs#101]
There appears to be a bug on UInt64 implementation. When we execute `value.lt(otherValue)` when `otherValue > value` we receive an error.

How to recreate:
```
import { Field, isReady, shutdown, UInt64 } from "snarkyjs";

const main = async () => {
    await isReady;
    const value1 = new UInt64(new Field("5000"));
    const value2 = new UInt64(new Field("10000"));
    value1.lt(value2);
}

Promise.resolve()
    .then(async () => await main())

shutdown();
```

Error:
```
Error: rangeCheckHelper: Expected 28948022309329048855892746252171976963363056481941560715954676764349967625337 to fit in 64 bits
```

**Comment by mitschabaude** [comment]
Thanks for reporting - will check it out

**Comment by mitschabaude** [comment]
I found this TODO comment which I think explains the bug:
https://github.com/MinaProtocol/mina/blob/feature/snarky-js-minimal/src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml#L278

**Comment by mitschabaude** [comment]
This is fixed by https://github.com/o1-labs/snarkyjs/pull/307!
