### ISSUE TITLE
Can't run server with snarkyJS dependency

### ISSUE THREAD

**Issue by 45930** [o1-labs/snarkyjs#1012]
I cannot run the server in my project because I am getting the following error in snarkyJS version 0.11.3

```
npm run dev

> mina-arena-server@1.1.0 dev
> npm run build && npm run start


> mina-arena-server@1.1.0 build
> npm run generate && tsc --project tsconfig.json


> mina-arena-server@1.1.0 generate
> graphql-codegen --config codegen.yml

✔ Parse Configuration
✔ Generate outputs
node_modules/snarkyjs/dist/node/lib/bool.d.ts:2:36 - error TS2307: Cannot find module 'src/bindings/crypto/non-negative.js' or its corresponding type declarations.

2 import { NonNegativeInteger } from 'src/bindings/crypto/non-negative.js';
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/snarkyjs/dist/node/lib/bool.d.ts:2
```

To repro, clone this repo at the linked commit, then run `npm i && npm run dev`

**Comment by mitschabaude** [comment]
This is a legit bug, there's a non relative import in the code https://github.com/o1-labs/snarkyjs/blob/ff908249a91da78c8347d8d5927037d2faf619b9/src/lib/bool.ts#L11

The problem seems to be that our CI somehow doesn't catch this..

**Comment by 45930** [comment]
The second one is tricky because it's my proof which has the error, but the it's in the generated typescript declaration file which is auto-generated.

**Comment by mitschabaude** [comment]
I think this should address both issues: https://github.com/o1-labs/snarkyjs/pull/1015

**Comment by 45930** [comment]
Confirmed!  Thank you so much @mitschabaude !
