### ISSUE TITLE
Add ES Lint rule: to avoid default export 

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#128]
To warn against using export default and instruct devs to use a named export for all smart contract classes.

**Comment by MartinMinkov** [comment]
PR for this here: https://github.com/o1-labs/eslint-plugin-snarkyjs/pull/6

**Comment by jasongitmail** [comment]
Awesome. Thanks @MartinMinkov! 

@ymekuria could you review this please?

**Comment by ymekuria** [comment]
This looks great @MartinMinkov. I reviewed and approved this pr https://github.com/o1-labs/eslint-plugin-snarkyjs/pull/6.
