### ISSUE TITLE
[BUG]: Using minfied build options leads to a broken build

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#138]
**Description**
When trying to build a release version of SnarkyJS and specifying minified options, the minified build seems to be broken. There is mention of 
```
Try calling \`await isReady\` before \`new ${t}()\``,pt=(t,e)=>`Cannot call static method because snarkyjs has not finished loading.
``` 
in the resulting `index.js` file that is created. This leads to weird and broken behavior when using SnarkyJS. 

**To build a minified version:**
1. Make sure you are on a branch that has the latest build deployed (`0.3.0`) -- branch `feature/deploy-txn`
2. Run `npm run build`
3. Run `NODE_ENV=production node --stack-trace-limit=100 src/build/buildNode.mjs --bindings=./dist/server/node_bindings/`

This results in the built SnarkyJS code having the error described above. It can be examined at `dist/server/index.js`

This leads to weird behavior when interacting with the `compile` and `deploy` methods.

**Comment by mitschabaude** [comment]
Another data point: I tried the latest published snarkyjs (0.3.3) in a simple project with the simple_zkapp examples (which includes running `compile`), and everything works fine.

My new hypothesis is that in the zkapp cli, snarkyjs is loaded twice somehow, and for one of the versions, `await isReady` is not called. Or, something else is special in that environment that breaks it.
