### ISSUE TITLE
Test the web version of snarkyjs in CI

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#151]
using puppeteer

**Comment by jasongitmail** [comment]
I.e. Create an MVP integration test in a real web browser

**Comment by mitschabaude** [comment]
with puppeteer!

**Comment by shimkiv** [comment]
Picking up https://github.com/o1-labs/snarkyjs/issues/407

**Comment by shimkiv** [comment]
@mitschabaude can we close it in favour of #407 / #411 ?
