### ISSUE TITLE
Convert the build to output ES6

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#17]
Todo: Check with Nathan & Martin to ask about their latest progress, before starting.

Issue: [JS of OCaml](https://github.com/ocsigen/js_of_ocaml/issues) only builds to CommonJS.

**Comment by mitschabaude** [comment]
Initial progress: I tried to see why the existing ES6 version (in the `joo-to-es6-module-fix` branch) doesn't run and it seems almost all of the errors stem from jsoo trying to access global variables from what it thinks is the global object, e.g. `jsoo_global.Uint8Array`, while we don't provide this stuff on our modified `jsoo_global`. This should be easy to fix.

However, see #18 for why I think that fixing this issue alone won't solve much
