### ISSUE TITLE
Finish remaining fields of party update

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#186]
- [ ] Set timing
- [ ] Set delegate
- [ ] Set zkApp URI
- [ ] Set votingFor

**Comment by mitschabaude** [comment]
[ ] timing

**Comment by mitschabaude** [comment]
also, have a nice API for these like
`this.account.zkappUri.set('http://...')`
`this.account.timing.verstingPeriod.set(..)`
