### ISSUE TITLE
Group - Group.endoScale is not a function

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#209]
**Description**

In the `snarky.d.ts` TS file, the `Group` class has a method on it called `endoScale`. [See here](https://github.com/o1-labs/snarkyjs/blob/a72606a293c7630025699fd6417659a67f9e70b8/src/snarky.d.ts#L593)

When this function is called, the following error is returned:

```file:///tmp/endo-test/build/src/index.js:3
const x = new Group(1, 1).endoScale(Scalar.random());
                          ^

TypeError: (intermediate value).endoScale is not a function
    at file:///tmp/endo-test/build/src/index.js:3:27
```

**Reproduce:**
The following code reproduces this error:
```
import { Group, Scalar, isReady, shutdown } from 'snarkyjs';

await isReady;

const x = new Group(1, 1).endoScale(Scalar.random());
console.log(x);

await shutdown();
```

**Comment by mitschabaude** [comment]
I think the short term fix is to remove that function. It's commented out in the ocaml code, don't know why
