### ISSUE TITLE
Group - Group.fromJSON always returns null

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#210]
**Description**

In the `snarky.d.ts` TS file, the `Group` class has a method on it called `fromJSON`. [See here](https://github.com/o1-labs/snarkyjs/blob/a72606a293c7630025699fd6417659a67f9e70b8/src/snarky.d.ts#L624)

When this function is called with any type of `JSONValue`, `null` is always returned

**Reproduce:**
The following code reproduces this error:
```ts
import { Group, isReady, shutdown } from 'snarkyjs';

await isReady;

// Different enumerations of `JSONValue`
const a = Group.fromJSON(1);
const b = Group.fromJSON(true);
const c = Group.fromJSON('1');
const d = Group.fromJSON([]);
const e = Group.fromJSON([1]);
const f = Group.fromJSON([1, 1]);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);

await shutdown();
```

**Comment by mitschabaude** [comment]
I guess the method should throw an error on these inputs. The proper json representation is `{x: string, y: string}`, where the string represents a Field. I also think we should stop accepting other types than string in Field.fromJSON, there should always be only one valid json representation, namely the same that toJSON returns
