### ISSUE TITLE
Int64 - `Int64(Field.one).neg()` just wraps around the max Field value

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#211]
**Description**
When calling `.neg()` on `Int64(Field.one)`, it returns `28948022309329048855892746252171976963363056481941560715954676764349967630336`. 

Is this correct behavior?

```ts
import { Int64, Field, isReady, shutdown } from 'snarkyjs';
await isReady;

const x = new Int64(Field.one).neg();
console.log(x.value.toString()); // 28948022309329048855892746252171976963363056481941560715954676764349967630336

await shutdown();
```

**Comment by mitschabaude** [comment]
This was correct in the old representation, however, it's outdated, the PR that I merged today changed the Int64 representation from one to two field elements, and the failing tests are all fixed (in this case, I changed the test to check that toString gives '-1')
