### ISSUE TITLE
Create a smart contract that can give us a feel for real-world performance & test in a browser

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#221]

**Comment by mitschabaude** [comment]
we should look at different circuit sizes and get a feel for how performance scales with that

**Comment by mitschabaude** [comment]
investigate overhead added by JS and Ocaml parts vs time spent in Wasm

**Comment by jasongitmail** [comment]
Gregor built a medium size example. We'll test again after the perf improvements are merged.

**Comment by jasongitmail** [comment]
Gregor did this with Sudoku which Matthew calculated was medium size circuit
