### ISSUE TITLE
Don't increment nonces on accounts that are the fee payer

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#271]
This is an important fix because with some upcoming changes on the protocol side, transactions will likely fail (or partially fail, which is even worse) if a fee payer is present in the other parties and also increments its nonce in that other party.

Here's how we could handle creation of a signed Party:

* see if there's a current transaction that has a fee payer
* if yes, look if our new party is the same account
* if yes, useFullCommitment. If no, incrementNonce

And here's how we should handle adding a fee payer to an existing transaction:
(this needs to happen in mina-signer as well! cc @MartinMinkov)

* see if the fee payer account is already present in other parties
* if yes, see if that other party increments its nonce
* if yes, throw an error.
* add the fee payer as usual

We also have to adapt the zkapp CLI, because in there we manually increment the nonce on the zkapp account which is also the fee payer. We should useFullCommitment instead.

**Comment by jasongitmail** [comment]
- [ ] Update SnarkyJS
- [ ] Update Mina Signer 
- [ ] Update Mina zkApp CLI

**Comment by mitschabaude** [comment]
I'm going to declare this closed with https://github.com/o1-labs/snarkyjs/pull/637, which covers snarkyjs. In mina-signer, I think we can wait for the re-implementation instead of changing the old version
