### ISSUE TITLE
Enforce limits on # of parties, events, & sequence events to match those defined by the protocol 

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#276]

**Comment by jasongitmail** [comment]
Ideally we throw a compile time error

**Comment by Comdex** [comment]
Hey! I don't know whether it is appropriate to ask here, because I only found this relevant open issue. How many fields is the limit size of each event and sequence event? And what is the total limit size of events and sequence events in each transaction?

**Comment by mitschabaude** [comment]
there's no extra limit for the number of fields in one (sequence) event, but there'll be a limit on the total number of all fields in all events / sequence events. We're still in the process of deciding the exact number, but it'll be about ~20-30 I think

**Comment by Comdex** [comment]
> there's no extra limit for the number of fields in one (sequence) event, but there'll be a limit on the total number of all fields in all events / sequence events. We're still in the process of deciding the exact number, but it'll be about ~20-30 I think

Personally, I prefer this limit >= 30, which I think would be more friendly to some privacy use cases based on the UTXO model, such as coin mixers.

**Comment by mitschabaude** [comment]
Most of these limits will be fairly tight, because the time budget for snark workers to create proofs workers becomes much tighter with zkApps

**Comment by jasongitmail** [comment]
Gregor explained well. We're trying to be conservative initially and then can potentially increase limits over time

**Comment by bkase** [comment]
Ask @deepthiskumar for the formula for the limits and translate the formula to the client side

**Comment by bkase** [comment]
The constants will probably change, but the formula probably won't change much
