### ISSUE TITLE
Implement API for sending MINA tokens via Party transactions

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#281]
# Description
During an internal discussion of the [Tokens RFC](https://github.com/o1-labs/snarkyjs/issues/233), the product team decided to not include an API for transfers of MINA for zkApps. We instead decided to punt on this for a later PR as we wanted more time to decide on an easy to use API.

Once we have a good design in place for tokens, this should be implemented as part of this issue.

**Comment by MartinMinkov** [comment]
# RFC

We wish to expose an intuitive and easy-to-use API for supporting sending MINA in party transfers. Adding transactions for MINA payments was discussed in #233 but was cut out of scope and should be implemented in another PR. Here, we propose an API that zkApp developers can use to support transactions with default MINA that is separate from the custom tokens API.

## Sending inside a zkApp method
An easy-to-use API should be exposed on the zkApp instance inside a method's execution. For example, a method name such as `send` can be attached to the `this` property inside a zkApp method. The send method will take as input an address to send MINA to as the receiver and the amount to send. The following code would be an example of such a method:

```ts
@method sendMINATokens(receiverAddress: PublicKey) {
    this.send({
        to: receiverAddress,
        amount: 10e9
    })
}
```
When the `sendMINATokens` method is invoked, the method will execute `this.send` with the specified properties. `this.send` will construct the parties necessary to represent a valid balance change in both the zkApp balance and the receiverAddress. 


## Sending using a constructed Party

In addition to exposing a way to send MINA tokens on a zkApp method execution, we would also like to support generating the parties structure by the zkApp developer outside of a zkApp. This can be done by adding a `send` method to the `Party` class inside SnarkyJS. This `send` method will behave similarly to the zkApp version by taking in an address to send to as the receiver and the amount. The following code would be an example of such method:

```ts
let party = Party.createSigned(privateKey); // create party from a private key
let party2 = Party.createUnsigned(publicKey); // Can also create a party from a public key but require authorization later before txn is submitted
party.send({ to: someAddress, amount: 10e9 }); // send MINA from the party's account
```
This way to construct a signed party and specify a send operation can be done inside a transaction block. This means that sending MINA in SnarkyJS isn't dependent on interacting with a zkApp and can be done anywhere a zkApp uses it.

The combination of these two approaches (inside a zkApp and with a signed party) should cover the primary use cases that a zkApp developer needs to send MINA in an easy-to-use way. 

## Testing

A suite of unit tests should verify that these methods behave correctly. The following test cases should cover these behaviors:
A zkApp successfully sends tokens when invoked in a smart contract method
A zkApp cannot send an amount greater than its current balance
A signed party sends MINA when used inside a transaction block
A signed party cannot send an amount greater than its current balance

**Comment by Trivo25** [comment]
clean and easy to use :)

**Comment by mitschabaude** [comment]
this looks great to me!

something I think we still have to improve is the naming of `Party.createSigned`, but that's an independent issue.

**Comment by ymekuria** [comment]
This is a very intuitive API. Nice work Martin!
