### ISSUE TITLE
Improve SnarkyJS README

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#291]
From Slack convo:
flesh out the [SnarkyJS README](https://github.com/o1-labs/snarkyjs/blob/main/README.md) with 
- a marketing-focused overview
- bullet points of benefits or key features to impart understanding quickly

In a ‘Ceviche multi-chain world’ where the README becomes a primary entry point for users, rather than the Mina docs, this content and context all become even more important.

_Future: We’ll add a brand graphic to the README after the rename is finalized._

**Comment by barriebyron** [comment]
We have more work to do, #866 is just a bare-bones starter update.

Future updates to provide:
- Marketing-focused overview
- Bullet points of benefits and key features to impart understanding quickly

**Comment by barriebyron** [comment]
Let's identify and answer these questions so that the updated README can inform the world about the awesome SnarkyJS uses:

1. who needs to know about SnarkyJS? 
2. what are the top 5 benefits of using SnarkyJS? 
3. what problems does SnarkyJS solve?
4. what is the call to action for this README? 
5. what is a compelling use case for SnarkyJS? 
6. what is the question you get asked the most about SnarkyJS?

**Comment by barriebyron** [comment]
Content inspiration
- include some code examples, so people can get a feel for what snarkyjs is like @mitschabaude 
- call to action IMO is starting a zkapp project with the zkapp cli, or try out snarkyjs in another way @mitschabaude

**Comment by stevenpack** [comment]
Some things I'd like to see (based on some of my favorite READMEs like https://github.com/BurntSushi/ripgrep)

- Badges (for CI etc.) if we have them
- Link to change log
- Link to contributing doc
- Link to docs (on the MF site)
- Bonus: A screen recording converted to a gif that shows how easy it is to download, scaffold a project and start building.

**Comment by mitschabaude** [comment]
> Bonus: A screen recording converted to a gif that shows how easy it is to download, scaffold a project and start building.

Great idea!

**Comment by barriebyron** [comment]
SnarkyJS is the best zero-knowledge SDK (gleaned from https://www.notion.so/minaprotocol/SnarkyJS-Feedback-14797844e7144d15bbb35fda7375c5e5 

SnarkyJS is the best zero-knowledge SDK
- Code is aesthetic and readable
- chaining API
- Separation of TypeScript and SnarkyJS
- Convenient stuff when you need it and out of the way when you don't

**Comment by barriebyron** [comment]
Still lots of work to do, iteration in https://github.com/o1-labs/snarkyjs/pull/886 before the next release so that npm is updated https://www.npmjs.com/package/snarkyjs
