### ISSUE TITLE
streamline releases

### ISSUE THREAD

**Issue by mimoo** [o1-labs/snarkyjs#31]
it'd be nice to leverage CI as much as possible to perform releases.

> (Optional) Automatic releases and changelog, using Semantic release, Commitizen, Conventional changelog and Husky (for the git hooks)

from https://github.com/alexjoverm/typescript-library-starter

@mitschabaude points to https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages also

**Comment by mitschabaude** [comment]
dupe
