### ISSUE TITLE
import `SelfProof` `ZkProgram` `verify` error

### ISSUE THREAD

**Issue by zhfnjust** [o1-labs/snarkyjs#312]
hello, I can't run [program.ts](https://github.com/o1-labs/snarkyjs/blob/main/src/examples/program.ts)

<img width="768" alt="image" src="https://user-images.githubusercontent.com/995909/182128061-b14fd9b4-b6e1-44b9-9bf0-680f11845ee4.png">

i found this error:

```
Module '"snarkyjs"' has no exported member 'SelfProof'.ts(2305)
```

my project is created by **zkApp Cli**,  snarkyjs version is `0.4.4`

**Comment by mitschabaude** [comment]
this is expected, because proof recursion is not published to npm yet. Usually, the snarkyjs `main` branch will be ahead of the latest released version. So, you can't expect that all examples in snarkyjs run with the latest version.
