### ISSUE TITLE
Change tsconfig.json `target` value to ES2020

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#32]
Izaak has reported that decorators don't behave as expected on the `feature/workshop-examples` branch. By changing the `target` value from `esnext` to `es2020`, the decorator error he was experiencing was fixed. Further work should be made to figure out why this was a breaking change.

Because `esnext` targets the highest version of TypeScript that the project supports, maybe we should be more conservative with how we specify the `target` value.

Playground link of correct behavior:
https://www.typescriptlang.org/play?ts=4.4.4#code/GYVwdgxgLglg9mABMOcAUAPAXIsIC2ARgKYBOAlIgN4BQNpxUIpSoksCiaUAFjAM44AhmACeAGkRQhpAOaNhYyQGtionPyikYYWZVqJDiCAn5wANsQB05uLLQByAYgCCDydLmMrJsJtIg0HCkiAC84a7kANw0RsamFta29g68YALuUnz80bFGvmaWNnaOUJme8lC5cQDyhABWxNBWACbEwDrEAAqkcAAOZFCi3DKVKmqSVIj8ClwYlKEAfNTxfonFKTNQUGQO5AC+kpU4aAvLDiakDNAO++Q0+w80QoT+QtDG5kL8-IgAQtQ6I86BAvj9XIhiBgdmAWr8AYC4gABFDoACMAAZ7nFsNMtDpZDE8oYClpAlBgqdEXEjPwQANSKdiXFeAIrBgwogHAB3Xq6BwxOKPR6kxBCTlgYjc1ynIkFdbJNBCdn3IA

Output should specify the variable `x` as the value "correct" when run. On commit `953cc6020966e90e36f3410237a64a0d16dcc6c5`, the same example is in `index.ts` and fails to set the variable correctly with the same code as the playground. To run the code on commit `953cc...`, run `npm run exec`

**Comment by mitschabaude** [comment]
Interesting! Here is more background on what exactly is the relevant change between es2021 and es2022:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

I tried it out and if you leave "target" at "esnext", but set `"useDefineForClassFields": false`, then you also get the "correct" behaviour. I don't have anything against switching to ES2020 right now, but it's good to know that our library users can still have esnext output if they want.

**Comment by mitschabaude** [comment]
FWIW, in the "esnext" version the class field is implemented by Typescript using an actual JavaScript class field:

```js
class A extends B {
    x;
    constructor() {
        super();
        this.x = 'wrong';
    }
}
__decorate([
    foo(10),
    __metadata("design:type", String)
], A.prototype, "x", void 0);
```
So we're sort of asking TS to break spec'ed JS behaviour. But I think no problem for now because decorators will take a while to come to JS, and will also be quite different in JS than now in TS, so we may want to revisit our assumptions of decorator behaviour when this time has come and not now.
