### ISSUE TITLE
how to get the preimage size for implementing  sha256

### ISSUE THREAD

**Issue by zhfnjust** [o1-labs/snarkyjs#320]
hello , I am implementing sha256.

before that i should know the preimage size to do the padding.

```
  export class Sha256 extends Circuit {
    @circuitMain
    static main(preimage: Field, @public_ hash: Field) {

      let size = preimage.toBits().length

    }
  }
```

but when calling `toBits().length`, it returns `255` all the tme.

so any idea to get the preimage size?

**Comment by mitschabaude** [comment]
Is there anything wrong with using `255`? That's the (max) bit length of a `Field`. (Sorry I'm not familiar with the sha256 algorithm)

**Comment by zhfnjust** [comment]
`sha256` algorithm need to append some padding bytes according the `preimage` length. but in this case I have no way of knowing the real size of the `preimage`。

**Comment by zhfnjust** [comment]
I also need to add a parameter `preimageSize: Field` to indicate.

**Comment by mitschabaude** [comment]
You could do that, yeah! But I still don't get what's wrong with always using 255 as the length

**Comment by zhfnjust** [comment]
another question:

 if i use slice()  on array when writing a circuit,  it crash right?

<img width="505" alt="image" src="https://user-images.githubusercontent.com/995909/182338879-dd1b9e51-da3a-42fe-8710-b46b1f1a0306.png">

**Comment by mitschabaude** [comment]
> if i use slice() on array when writing a circuit, it crash right?

no! the code inside a circuit is normal JavaScript. Normal JS doesn't crash when you use slice on an array, except when that array is undefined or something like that.

**Comment by mitschabaude** [comment]
Closing this issue, let's continue debugging in discord
