### ISSUE TITLE
The latest version(0.5.1) does not export the JSONValue type 

### ISSUE THREAD

**Issue by Comdex** [o1-labs/snarkyjs#353]
```typescript
import { JSONValue } from 'snarkyjs';  // error
```
Has this type been converted to an inner type？

**Comment by mitschabaude** [comment]
Yes - it's an oversight that this is not in our changelog. Many inessential exports have been removed. Do you think we should export JSONValue?

**Comment by Comdex** [comment]
> Yes - it's an oversight that this is not in our changelog. Many inessential exports have been removed. Do you think we should export JSONValue?

If we can use the toJSON() method of CircuitValue directly, I think it is necessary to export JSONValue.

**Comment by mitschabaude** [comment]
I think we want to replace APIs like this:
```ts
Field.fromJSON(json: JSONValue): Field | null;
Bool.fromJSON(json: JSONValue): Bool | null;
```
with APIs like this:
```ts
Field.fromJSON(json: string): Field;
Bool.fromJSON(json: boolean): Bool;
```
If we do that, maybe we don't even need the `JSONValue` type anymore
