### ISSUE TITLE
Make branch where hard-coded circuit size limit is changed

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#380]
This would be in support of anyone who needs to use snarkyjs with a bigger circuit than currently supported

Impact: This is currently blocking an implementation of SHA-256, which is a highly valuable experiment with snarkyjs, cc @xhliu @zhfnjust 
https://github.com/o1-labs/snarkyjs/issues/328

The issue refers to non-pickles circuits, which don't get deployed to Mina, for which there is no size limit imposed by verifier circuits on the network! It seems that there shouldn't be any fundamental issue preventing us from making these circuits as large as necessary.

This issue entails just changing any hard-coded values in both the OCaml & Rust code to change the size limits, so that interested people can work with larger circuits, and making a branch with modified snarkyjs bindings which make that change accessible

This would be _a first step_ in the direction of making the size limit for plain (non-Pickles) circuits configurable in snarkyjs

Here is one known place where the size of the domain (lagrange basis) is hard-coded to 2^16, which currently affects snarkyjs:
https://github.com/MinaProtocol/mina/blob/48b44c16bcc704efb7c67fdfdcf4a14d3877e4da/src/lib/crypto/kimchi_backend/pasta/basic.ml#L17

From first experiments by @Trivo25, it seems that changing the limit is more involved than just changing this value

**Comment by xhliu** [comment]
Code is here https://github.com/sCrypt-Inc/snarkyjs-sha256

**Comment by haoustc** [comment]
我们也在开发相关功能，请问这个限制什么时候可以去掉呢？热烈期盼中。

**Comment by haoustc** [comment]
we are also doing some development in sha256 circuit, when will the limit be removed? expecting.

**Comment by mitschabaude** [comment]
This branch exists now: https://github.com/o1-labs/snarkyjs/pull/496

However, when trying doubling hashing from the [snarkyjs-sha256](https://github.com/sCrypt-Inc/snarkyjs-sha256) repo, the prover runs into an out-of-memory error, apparently hitting the hard 4GB limit on the Wasm memory size.
![image](https://user-images.githubusercontent.com/20989968/196783696-70d30afd-3481-4dc9-b305-1694914894e1.png)

I'm closing this and will raise the issue of high memory consumption with our crypto team, but this is likely not something that can be fixed in the near term.
