### ISSUE TITLE
Document tx construction, account updates, compiling, proving and signing

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#381]

**Comment by mitschabaude** [comment]
In my judgement, this is the most important open doc issue we have currently, and I want to pursue it before testnet launch.

Here's a proposal:
* We add a new explainer section, maybe titled "Transactions, account updates and proofs", at the bottom of "How to write a zkApp"
* We give succinct descriptions of what transactions and account updates are in Mina/snarkyjs
* We introduce the `Mina.transaction` API, in generality -- i.e. without reference to any specific flow like "interacting with Auro wallet via Mina provider" or "running a unit test with Jest". (These specialized use cases should live in later sections IMO.)
* We explain how account updates are typically created under the hood by more high-level methods, and we give a concrete example: creating a payment with the `send` API
* We explain how calling a zkApp creates an account update under the hood (which needs a proof for authorization)
* We show how to use the `Mina.transaction` output to create a proof, and how you have to compile the SmartContract first
* We hint at how the finished transaction would be used in a web app -- passed to the wallet via Mina provider and signed there. (When it exists, we would link to the Mina provider docs here.) We also explain how a transaction can be signed and sent with snarkyjs alone (hint at use cases: testing, server-side/automated interaction with Mina)

**Comment by mitschabaude** [comment]
Further thing that came up:
we should document how to fetch accounts and explain the caching that we do in some places. `Mina.fetchAccount` vs `Mina.getAccount`, `zkApp.x.fetch()` maybe

**Comment by mitschabaude** [comment]
More stuff that came up: it should be documented that the transaction code runs multiple times, so using mutated global state as method inputs is not supported
