### ISSUE TITLE
Can multiple types of reducers be declared in the same zkApp?

### ISSUE THREAD

**Issue by Comdex** [o1-labs/snarkyjs#397]
Or another way to ask is it possible to define multiple different types of sequence events in the same zkApp? (This should require a zkApp to have multiple sequence states?)

It should look like this:
```typescript
reducer = Experimental.Reducer({ actionType: Note });
reducer2 = Experimental.Reducer({ actionType: Field});
```

I know that we can use a composite CircuitValue to combine these types as a sequence event, but since snarkyjs does not support plain if statements, what I understand is that this can only handle relatively simple single data or relatively simple logic. For a sequence event with different types of data, you also need to use dummy data (Not all processing can use dummy data, and calculations that do not conform to the Circuit.if judgment also need to be side-effect-free). For example, it would be difficult for a zkApp that holds two or more different merkle roots to use the same sequence event to perform the update calculation of these roots.

**Comment by mitschabaude** [comment]
no, not possible. to implement multiple types of actions, you can create an `actionType` that represents one of many actions at the same time. for example:

```ts
class MyCompositeAction extends CircuitValue {
  @prop note: Note;
  @prop fields: Field;
  @prop isNote: Bool
}

class MyContract extends SmartContract {
  reducer = Experimental.Reducer({ actionType: MyCompositeAction });
}
```

you then could have one `reduce` operation which ignores actions that have `isNote = true` and one which ignores ones with `isNote = false`

**Comment by Comdex** [comment]
Ok, I get it, it's just that sometimes it's really tricky to implement ignore 🤦🏻

**Comment by mitschabaude** [comment]
maybe this helps:
```ts
(state, action) => {
  let { note, field, isNote } = action;
  let stateForNewNote = reduceNote(state, note);
  let stateForNewField = reduceField(state, fields);
  return Circuit.if(isNote, stateForNewNote, stateForNewField);
}
```

**Comment by Comdex** [comment]
Thanks. In fact, the most troublesome thing is the handling of dummy data.
