### ISSUE TITLE
Replace Safari-breaking RegExp with function

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#415]
It's in `removeJsonQuotes`: https://github.com/o1-labs/snarkyjs/blob/235dc35450132090414592225c0522874fe266d0/src/lib/fetch.ts#L577-L583

The task is to get rid of the ReqExp in there, or replace it with one that works in Safari.

Requirements:
Should remove the quotes from the keys of an arbitrary JSON object (but not quotes in string values)
Should handle any escaped quotes in string values. Can assume keys don't have escaped quotes.

**Comment by mitschabaude** [comment]
it's in `removeJsonQuotes`

**Comment by shimkiv** [comment]
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/4096154/190239590-f51f1387-2c7b-4ba1-91c4-a9ead12a71b0.png">
