### ISSUE TITLE
prevent conflicting permission/updates in the same AccountUpdate

### ISSUE THREAD

**Issue by Trivo25** [o1-labs/snarkyjs#424]
Currently, the protocol only allows us to attach one authorization kind (either proof, or sig) to the tx, but AccountUpdates could include multiple updates that are conflicting depending on their permissions.

For example, a zkApp account could try to update the appState (which requires a proof) and set the delegation (which requires a signature) within the same AccountUpdate - but signing an AccountUpdate will not allow an additional proof

**Comment by mitschabaude** [comment]
I think this is resolved right, with your permission checking PR landed?
