### ISSUE TITLE
Fix `fetchMissingData` with remote blockchain

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#430]

**Comment by mitschabaude** [comment]
doesn't seem to do the right thing anymore
causing stuff like
`Error: x.get() failed, because the zkapp account was not found in the cache. Try calling `await fetchAccount(zkappAddress)` first.`

**Comment by shimkiv** [comment]
https://github.com/o1-labs/e2e-tests/issues/34

**Comment by shimkiv** [comment]
Issue still persists.
- Deploy [zkApp](https://github.com/o1-labs/e2e-zkapp/blob/develop/e2e-zkapp-sc/src/E2eZkApp.ts) with some initial account state (say, `appState[0] = 2`);
- In SnarkyJS Web version reload the page after SC deployment to make sure the state won't be available and zkApp SC instance will be re-instantiated if needed;
- Invoke zkApp's method with some constraints (for example the `update` one passing same value `2` as was used with deployment) by calling it in Web version, similarly to [updateOnChainZkAppStateWeb()](https://github.com/o1-labs/e2e-zkapp/blob/develop/e2e-zkapp-ui/public/javascript/helpers.js#L403) method.

SC method invocation will result in the error like this `"Error: assert_equal: 0 != 2"`, where `0` means that the current state of the account is unknown.
But should you manually fetch the account's state after this, like calling the `await fetchAccount(...)`, and invoke `update` method again - you will receive the correct (for this SC) error `"Error: assert_equal: 4 != 2"`, where `4` means that now account's state reflects the truth.
