### ISSUE TITLE
Failure to verify proofs in the browser

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#474]
![image.png](https://images.zenhubusercontent.com/6221c39815ade7e04617f387/5e0b807e-e604-412e-a3b5-33d0df694f96)

it seems the wasm js bindings need to be updated, and this should be added as a test to the browser e2e test

**Comment by shimkiv** [comment]
@mitschabaude 
Are you talking about the following to be added into the tests?

```typescript
    const {verificationKey} = await E2eZkApp.compile()
    const proof = await transaction.prove()
    verify(proof[0]!, verificationKey.data)
```
