### ISSUE TITLE
Remove `Field.fromNumber(x)` to reduce API surface area

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#486]
Given `Field(x)` works equally well.

**Comment by mitschabaude** [comment]
we have three similar methods, which all duplicate part of the `Field()` constructor

```ts
  static fromString(x: string): Field;
  static fromNumber(x: number): Field;
  static fromBigInt(x: bigint): Field;
  ```
  
the only things they add is to narrow down the types that are allowed as input. I'm not sure if that adds any value though, and haven't seen any of those three used in any actual code

**Comment by bkase** [comment]
Remove them on UInt* as well

**Comment by bkase** [comment]
Sadly, we should remove Field.zero and Field.one and Bool.true and Bool.false
