### ISSUE TITLE
Refactor web workers to be spawned from the main thread, for Safari support

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#490]
Safari has a bug where web workers can't be spawned from other web workers. This is what we currently do in snarkyjs though, which makes snarkyjs not work in Safari.

https://stackoverflow.com/questions/64045547/javascript-referenceerror-cant-find-variable-worker-in-safari-when-creating/65099653#65099653

TODO: refactor the code in `src/chrome_bindings` (entry point: `plonk_init.js`) to start all workers directly from the main thread.

Right now, the main thread spawns one "main worker", which spawns the other workers. This extra level was introduced so that we can use `Atomics.wait`, which is used in compiled Rust code for concurrency, and which is not allowed on the main thread in browsers. As an alternative solution, I propose to keep the architecture as is, but have the "main worker" tell the main thread to spawn sub-workers.

**Comment by mitschabaude** [comment]
Turns out this is already fixed in Safari Technology Preview. https://github.com/WebKit/WebKit/commit/48880e342359f100878b1b87373e706db7dfe540

It seems to me that we should probably just wait for that fix to land in mainstream Safari, instead of refactoring our Worker code.

**Comment by shimkiv** [comment]
macOS Ventura 13.0.1 (22A400), Safari Version 16.1 (18614.2.9.1.12)
- Still same issue as [before](https://github.com/o1-labs/snarkyjs/pull/419#issuecomment-1250215126)
