### ISSUE TITLE
Discuss error handling for failed assertions & other exceptions during contract execution

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#492]
We need to document a recommended best practices to capture specific assertion failures so that a dev can expose helpful feedback to their end users in their UI.

**Comment by MartinMinkov** [comment]
[This](https://github.com/o1-labs/snarkyjs/issues/286) will be helpful for devs that want a way to expose custom error messages with assertion methods! 

I have a few PRs in flight that will allow this.
https://github.com/o1-labs/snarkyjs/pull/470

**Comment by mitschabaude** [comment]
We discussed this and came up with a recommendation that was put on the docs: https://docs.minaprotocol.com/zkapps/how-to-write-a-zkapp-ui#displaying-assertion-exceptions-in-your-ui
