### ISSUE TITLE
Proving bug in Dex

### ISSUE THREAD

**Issue by bkase** [o1-labs/snarkyjs#498]
This happens when creating a proof for `Dex.redeemLiquidity()`

In the Pickles wrap prover, the `compute_witness` step (in `Plonk_constraint_system`) fails when it tries to access `external_vars` at out-of-bounds indices.

The fact that this is the wrap prover makes the issue more mysterious because we wouldn't expect the wrap circuit to be influenced by a badly written snarkyjs circuit (which, for example, created less witnesses than expected or similar)

**Comment by Trivo25** [comment]
Quick update: The bug seems to be caused by the method `TokenContract.approveUpdateAndSend(zkappUpdate: AccountUpdate, to: PublicKey, amount: UInt64)`, more specifically, the `AccountUpdate` as argument. Removing `AccountUpdate` from the methods signature doesn't cause proving to fail `approveUpdateAndSend(to: PublicKey, amount: UInt64)`

**Comment by Trivo25** [comment]
The bug only appears when we try to prove an `AccountUpdate` (pass it as an argument to another zkApp method) where the authorization is either `None_given` or `Proof`, whereas signing the `AccountUpdate` (authorization: signature) works. 

The bug appears when trying to prove the transaction (add the missing proofs to all `AccountUpdate`s via the `provers` array https://github.com/MinaProtocol/mina/blob/develop/src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml#L2215) 

```
panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', src/arkworks/pasta_fp.rs:59:21 
```

this error can be traced back to https://github.com/MinaProtocol/mina/blob/develop/src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml#L464

where it seems like `x` is not being computed correctly(?) https://github.com/MinaProtocol/mina/blob/develop/src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml#L444
