### ISSUE TITLE
Remove static members that are replaceable by constructor invocations

### ISSUE THREAD

**Issue by bkase** [o1-labs/snarkyjs#511]
This means we should remove Field.zero and Field.one and Bool.true and Bool.false

**Comment by mitschabaude** [comment]
There's also `Field.minusOne`, and `UInt.{one,zero}`, and `Int.{one,zero,minusOne}`

**Comment by bkase** [comment]
I don't see UInt or Int constants in here and it looks like the bool ones were already removed

**Comment by mitschabaude** [comment]
here!

https://github.com/o1-labs/snarkyjs/blob/928bc47ec2e568bc159ab0d468cb282747d9a788/src/lib/int.ts#L13-L19

https://github.com/o1-labs/snarkyjs/blob/928bc47ec2e568bc159ab0d468cb282747d9a788/src/lib/int.ts#L205-L211

https://github.com/o1-labs/snarkyjs/blob/928bc47ec2e568bc159ab0d468cb282747d9a788/src/lib/int.ts#L13-L19

https://github.com/o1-labs/snarkyjs/blob/928bc47ec2e568bc159ab0d468cb282747d9a788/src/lib/int.ts#L494-L502

**Comment by mitschabaude** [comment]
@bkase actually we should probably wait on the simplified `UInt32(number)` constructors before removing these constants

**Comment by bkase** [comment]
ah okay, they're just not used by us yet I guess

**Comment by mitschabaude** [comment]
We use them quite a bit!

**Comment by mitschabaude** [comment]
![image](https://user-images.githubusercontent.com/20989968/199316998-cd9de96f-7a55-4396-a8ec-519ac5bbf550.png)
