### ISSUE TITLE
ZkProgram methods return their return values rather than require them as arguments

### ISSUE THREAD

**Issue by bkase** [o1-labs/snarkyjs#523]
Specifically, we'd want methods like this recursive add rollup method:

To go from:

```typescript
method(
        publicInput: Field,
        left: SelfProof<Field>,
        right: SelfProof<Field>
      ) {
        left.verify();
        right.verify();
        // assert that the left and right equal this input
        left.publicInput.add(right.publicInput).assertEquals(publicInput);
      },
```

to

```typescript
method(
        left: SelfProof<Field>,
        right: SelfProof<Field>
      ): Field  {
        left.verify();
        right.verify();

        return left.publicInput.add(right.publicInput);
      },
```

This would make the API more "snarky"

**Comment by bkase** [comment]
Requires some refactoring of the SnarkyJS/OCaml glue and some other info exposed from Pickles to do properly.

**Comment by mitschabaude** [comment]
Yes, that would do it! I'd prefer using the "public output" thing that's already built into Pickles, not sure if that also involves re-running the logic first.

**Comment by bkase** [comment]
This is good hack in the meantime though! Given that pickles changes are complex

**Comment by nicc** [comment]
IRI: @mitschabaude / @Trivo25
