### ISSUE TITLE
[feature request] Decouple signing from transaction creation

### ISSUE THREAD

**Issue by mirceanis** [o1-labs/snarkyjs#53]
In current snarkyjs (v0.1.11) creating and sending a transaction looks like this:
```ts
await Mina.transaction(senderPrivateKey, async () => {
    // transaction code
  })
    .send()
    .wait();
```

This means that the frontend code that creates the transaction and waits for it also has access to the private key.
I think it would be very useful to be able to create transactions without having direct access to the key, but rather by getting access to a signer object.

A back of the napkin example would be something like this:

```ts
interface MinaSigner {
  sign: (data: Uint8Array) => Promise<Uint8Array>
}

class SimpleSigner implements MinaSigner {
  constructor(privateKey: string) {}
  async sign(data: Uint8Array): Promise<Uint8Array> {
      // ...implement the actual signing
  }
}

const senderSigner = new MinaSigner(senderPrivateKey)

await Mina.transaction(senderSigner, async () => {
    // transaction code
  })
    .send()
    .wait();
```

The benefit of this approach is that you can separate concerns more cleanly between key management and frontend code.
You can let a wallet or an HSM handle keys and not have to trust that the frontend has no vulnerability that allows someone to sniff keys.

**Comment by mitschabaude** [comment]
Hey, thanks a lot for the feedback. This is on our testnet roadmap, the idea is that snarkyJS will only handle the transaction construction, and signing/sending is done by either another library or - preferably! - by interfacing with a browser wallet. We are in contact with the Auro wallet to make that work.

It's good to have it in its own github issue!

**Comment by mirceanis** [comment]
Excellent!

I'm developing a framework for verifiable data and decentralized identitiy (https://veramo.io) and would like to integrate snapps and some snarkyjs circuit logic.

This separation of concerns is very important, since these 2 aspects of transaction lifecycle don't always live in the same app, or even on the same machine.

An intermediate solution is to be able to serialize/deserialize signed transactions.
This way, the "signer" can act on a higher level and also build the transactions, not just sign blind data, but then the logic that sends transactions and waits for them can still live in a frontend.

Does this make sense?
I think serializing signed transactions is important for its own sake. I can create a different issue for that if you agree :)

**Comment by mitschabaude** [comment]
Makes sense to me!

Re: serializing transactions, to interact with browser extension we will have to send transactions with [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), and if that works then serialization is probably only a small step away. So I think it can stay coupled to this issue.

**Comment by mitschabaude** [comment]
This is done -- in current snarkyjs, you can leave out the fee payer key and sign with mina-signer
