### ISSUE TITLE
Nullifier RFC

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#538]
@bkase and @mimoo are going to research and decide what design would be most useful for us to pursue.

**Comment by bkase** [comment]
We decided not to prioritize digging into this too much for now, but I figured I'd share my rough framework for evaluating choices if it helps: Namely, we should do whatever is the most standard, simplest, easiest to build even if it's not ideal by other means just so we have something in place, as a non-ideal implementation is better than nothing. Afterwards we can follow up with a "better" version should we choose to. I think @mitschabaude has more detailed choices that he can share here too.

**Comment by mitschabaude** [comment]
I think we have a choice though whether we use [Semaphore nullifiers](https://worldcoin.org/the-worldcoin-protocol) (which I [implemented in Bogota](https://github.com/mitschabaude/mina-world-id), without the storage part) or [Aayush Gupta's newer nullifier scheme](https://eprint.iacr.org/2022/1255.pdf) (which is better-suited, mainly because it doesn't require the private key as smart contract input)

**Comment by mitschabaude** [comment]
Requirements for a solution:
- Can prove inclusion / non-inclusion of nullifiers in a sparse Merkle tree, inside smart contract
- In a way which allows for concurrent user transactions
- and doesn't blow up the circuit size limit

Some ideas for making that happen are:
- use Matt's trick to get width-3 Merkle trees for the price of binary ones (add third element to the hash of the first two)
- split Merkle tree hashing between the method which dispatches the action and the reducer method
- ZkProgram to do the hashing off-chain

**Comment by bkase** [comment]
I don't think we should include these special tricks in the initial deliverable on this (but could consider in follow-ups)

**Comment by mitschabaude** [comment]
I also wouldn't include them in the deliverable, but I would include practical usability in the deliverable -- i.e. the requirements I listed. If there's a grant then the result should be useful

**Comment by jasongitmail** [comment]
Closing b/c we have a new RFC for a nullifier.
