### ISSUE TITLE
Improve GraphQL error handling

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#540]
From @es92. More details weren't given; if can provide more detail, that could be helpful during team discussion. 

> Expose GraphQL prints / errors programmatically instead of just the console

**Comment by es92** [comment]
Currently GraphQL requests print to the console, but they aren't available to the program as an object. I'd propose they be returned as an object, for the developer's code to inspect, and optionally print (or not as desired)

**Comment by mitschabaude** [comment]
This makes sense!

**Comment by mitschabaude** [comment]
this is done
