### ISSUE TITLE
Usage of If Conditional rather than Circuit.If

### ISSUE THREAD

**Issue by ckartik** [o1-labs/snarkyjs#547]
I'm curious how snarky is able to use an if branch statement from javascript in the snarky.js code. I was under the assumption that since this compiles to a circuit, that wouldn't be possible. Code [here](https://github.com/o1-labs/snarkyjs/blob/0f17d725d004bda9ac1ca6a9b896713258a5d55e/src/lib/encryption.ts#L12-L63).
```typescript
    let keyStream = sponge.squeeze();
    let encryptedChunk = message[i].add(keyStream);
    cipherText.push(encryptedChunk);
    
    // Here you can see the use of if statments.
    if (i % 2 === 1) sponge.absorb(cipherText[i - 1]);
    if (i % 2 === 1 || i === message.length - 1) sponge.absorb(cipherText[i]);
  }
  ```

**Comment by mitschabaude** [comment]
The answer is that JS is not compiled. It is just executed to add constraints to a circuit. You can see the if conditions as a sort of metaprogramming, which determine what constraints to add to the circuit.

@ckartik I'd be interested what part of our docs/material gave you the assumptions that JS compiles to a circuit, and that you can't use if statements like we use them here. I'd like to fix this since it's a misconception that I've seen very often.

**Comment by ckartik** [comment]
I don't think I follow, so if I import the encrypt function from snarky, it doesn't actually import the branching logic the encrypt function consists of. I'm guessing this all compiles down to a circuit.

To reply to your second point I think having a mental model of the compilation process (like the one I currently have for traditional sequential programs or interpreted languages) is important. I noticed you've got extensive details in the O(1) Labs notebook, and I'll take a look at it. Having a mid-level description in the Mina docs would be helpful. I find the high-level description to be too high-level to yield value and the O(1) Labs notebook details to be too low-level for me to quickly iterate with the technology and learn along the way. Hope this helps! You guys are doing an amazing job! 😄

**Comment by mitschabaude** [comment]
> I'm guessing this all compiles down to a circuit, so I don't quite understand why the imported logic wouldn't as well?

No - zkApp code (both user-written and the code in our lib) doesn't "compile down to a circuit", in the sense that JS is transformed into something else. Instead, the way snarkyjs works, is that the JS code (for example, the SmartContract method) is _executed_, and the different functions (like Field.add, Poseidon.hash,..) add constraints to a current circuit while they run.

So the code you write can be any Javascript, that, when executed, creates the constraints that you want. As such, there's no limitation on what JS language constructs you can use.

**Comment by mitschabaude** [comment]
> Having a mid-level description in the Mina docs would be helpful.

This is good feedback. We were discussing internally about adding a "snarkyjs under the hood" section that would explain stuff like this.
