### ISSUE TITLE
Rename: `Experimental.Callback` -> `Experimental.TokenCallback`

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#562]
## Description

Taken from [this](https://github.com/o1-labs/docs2/pull/104/files#r1019728713) comment on a PR regarding docs on custom tokens.

To quote:
"Callback is token specific right? If so, we might want to think of a different name like TokenCallback b/c otherwise we risk devs thinking it's a generic and trying to use it for other purposes. ..."

This brings up a good point about the naming of `Callback.` It's intended purpose is to be used to approve token transfers, however, it can be used in a general way for a zkApp to generate AccountUpdates from other methods.

**Comment by mitschabaude** [comment]
-1. Callback is not token-specific and it's fine to use it for other purposes. Callback is just a nicer way of calling a method, taking the account update that it produced and passing that account update as input to a different method (well, not sure it's actually "nicer" with the current API, but it could be)
