### ISSUE TITLE
Rationale for large address size

### ISSUE THREAD

**Issue by ckartik** [o1-labs/snarkyjs#564]
Unlike Ethereum which takes the last 20 bytes of the hash of the public key, Mina uses a 55-byte address. Since a Field element is bounded to ~32 bytes of data, what was the rationale for using such a large address size? It makes computation with addresses hard, I'm curious what the tradeoffs were?

**Comment by mitschabaude** [comment]
This should probably be an issue on the [Mina repo](https://github.com/MinaProtocol/) where this decision was made long ago. What I can say is that our addresses have the beautiful property that they _are_ the public key, so they can be used directly for other things you do with public keys, like verifying signatures. In a sense it's simpler than to have two separate concepts of "public key" and "address" and to store both of them.

Maybe @bkase can give actual insights into why our approach was chosen!

**Comment by ckartik** [comment]
I appreciate the public key being the address. I guess it's possible a Field was 512 Bits in size. I recall reading that Mina reduced the Field Size for circuit performance. Thanks for the response!

**Comment by mitschabaude** [comment]
A Field actually has just 255 bits / 32 bytes, but the size blows up by base58 encoding I guess
