### ISSUE TITLE
Add back timestamp precondition by wrapping global slot

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#579]
This PR: https://github.com/MinaProtocol/mina/pull/12234
removes the timestamp precondition. However, that precondition is a very user-friendly way to access the current time in a smart contract. We should bring it back on the `berkeley` branch by adding a wrapper around `globalSlotSinceGenesis`

**Comment by jasongitmail** [comment]
needs mini RFC
