### ISSUE TITLE
[BUG] UInt64.assertGt and UInt32.assertGt do not work correctly

### ISSUE THREAD

**Issue by Comdex** [o1-labs/snarkyjs#58]
https://github.com/o1-labs/snarkyjs/blob/e08f981166be59d962e9cfa196da1ae7e33f1368/src/lib/int.ts?_pjax=%23repo-content-pjax-container#L153

Hi, these two methods(**UInt64.assertGt and UInt32.assertGt**) do not work correctly, as shown in the code. Is the assertGte method also missing?

**Comment by 0b01** [comment]
Do you have a minimal reproducible example? It appears to be correct as `a < b === b > a`

**Comment by mitschabaude** [comment]
Agreed that the `assertGt` code looks correct, and agreed that `assertGte` is missing. Will fix the latter

**Comment by Trivo25** [comment]
I believe this can be closed?
