### ISSUE TITLE
verifying a `ZkProgram` proof inside a smart contract breaks 

### ISSUE THREAD

**Issue by Trivo25** [o1-labs/snarkyjs#605]
works before SnarkyJS `0.7.0`

```ts

let MyProgram = Experimental.ZkProgram({
  publicInput: Field,

  methods: {
    baseCase: {
      privateInputs: [],

      method(publicInput: Field) {
        publicInput.assertEquals(Field(0));
      },
    },
  },
});

class MyProof extends Proof<Field> {
  static publicInputType = Field;
  static tag = () => MyProgram;
}

class SimpleZkapp extends SmartContract {
  deploy(args: DeployArgs) {
    super.deploy(args);
    this.setPermissions({
      ...Permissions.default(),
      send: Permissions.proof(),
    });
  }

  @method verify(p: MyProof) {
    p.verify(); // no good
  }
}

```
`bad verify: dlog_check`

edit: bindings need to be updated to include the original fix https://github.com/MinaProtocol/mina/pull/11698

after some investigating, i figured using the bindings from https://github.com/MinaProtocol/mina/pull/11698 work for both the example above as well as https://github.com/o1-labs/snarkyjs/blob/main/src/examples/program.ts#L53
but a newer change in the mina repo broke both code snippets, not sure which one yet - it seems to be similar to https://github.com/MinaProtocol/mina/issues/11389, which has been fixed a while ago and worked fine after the fix

**Comment by mitschabaude** [comment]
noooo! 😭 

> but a newer change in the mina repo broke both code snippets, not sure which one yet

that's a great find, could mean this can be fixed fairly easily.

we need a unit-test in the Mina repo to prevent this in the future!
