### ISSUE TITLE
`ZkProgram` integration test

### ISSUE THREAD

**Issue by Trivo25** [o1-labs/snarkyjs#615]
The recursion API is arguably one of SnarkyJS' main feature, and will potentially play an important building block in larger zkApp applications, yet we dont have any tests for it, which allows to easily sneak in bugs or small mistakes like this one https://github.com/o1-labs/snarkyjs/issues/605

TODO first: fix https://github.com/MinaProtocol/mina/blob/develop/src/lib/snarky_js_bindings/test_module/inductive-proofs.js

**Comment by mitschabaude** [comment]
I think the most important item would be improving the recursion test which is already in the Mine repo (since that is where recursion is most likely to break): https://github.com/MinaProtocol/mina/blob/develop/src/lib/snarky_js_bindings/test_module/inductive-proofs.js
