### ISSUE TITLE
Regression testing to check that snarkyjs changes don't change deployed circuits

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#621]

**Comment by Trivo25** [comment]
We could just add a basic verification key comparison to all our integration tests as a short term solution. thoughts?

**Comment by mitschabaude** [comment]
> We could just add a basic verification key comparison to all our integration tests as a short term solution. thoughts?

I like this idea! We could simply have a command that dumps these into a file, which is checked into git. Then we see when they change. CI could simply check demand consistency of these dumped vk hashes which the current code
