### ISSUE TITLE
A type error occurs when a Struct containing an array is used as an on-chain variable

### ISSUE THREAD

**Issue by Comdex** [o1-labs/snarkyjs#625]
This is a test after applying the #567 update：
```typescript
class MyStruct extends Struct({ a: Field }) {}

class MyStructB extends Struct({
  a: Circuit.array(Field, 5),
}) {}

export class TestZkapp extends SmartContract {
  @state(MyStruct) myStruct = State<MyStruct>(); // work
  @state(MyStructB) myStructB = State<MyStructB>(); // type mismatch error
}
```

**Comment by mitschabaude** [comment]
Thanks! The issue makes sense to me - the type error occurs when the state is guaranteed to consist only of field elements, and Circuit.array doesn't currently return a type which distinguishes this case (in contrast to Struct itself)
