### ISSUE TITLE
The execution result of SmartContract.analyzeMethods() cannot display 'rows'

### ISSUE THREAD

**Issue by Comdex** [o1-labs/snarkyjs#626]
Example code:
```typescript
export class Add extends SmartContract {
  @state(Field) num = State<Field>();

  init() {
    super.init();
    this.num.set(Field(1));
  }

  @method update() {
    const currentState = this.num.get();
    this.num.assertEquals(currentState); // precondition that links this.num.get() to the actual on-chain state
    const newState = currentState.add(2);
    this.num.set(newState);
  }
}

let result = Add.analyzeMethods();
console.log('Add analyze result: ', result);
```

Screenshot of the result:
![issue](https://user-images.githubusercontent.com/3725514/205472806-c7c3f3da-c5a4-459c-aa81-7823b94cb1a6.PNG)

Also, does ZkProgram have a method similar to analyzeMethods?

**Comment by mitschabaude** [comment]
Thanks! I noticed this recently as well and it's already fixed in a PR: https://github.com/MinaProtocol/mina/pull/12123

`ZkProgram` currently only has `digest()` for the digest, but it would be very easy to add `analyzeMethods()`

**Comment by mitschabaude** [comment]
done
