### ISSUE TITLE
Make test accounts have normal permissions

### ISSUE THREAD

**Issue by 45930** [o1-labs/snarkyjs#638]
Repro steps:

Fill in a user private key in this script and attempt to run (private key must be to a funded account on Berkeley).  **Expected behavior** is that the funded account will send the smart contract 1000 base units of Mina, and the contract state (merkle root) will update to reflect the user's deposit.  **Observed behavior** is that the transaction gets built just fine but gets an error on the blockchain [for example](https://berkeley.minaexplorer.com/transaction/CkpZ5gkKzH8ir83oitm3F349DuQN266GFrgTh95tC4FM4BWoLf6FE).  The current root hash on the chain is `2273112294...`.  If that root hash has changed, then that probably means a deposit has worked and the error is resolved.

Script:
https://github.com/pico-labs/coinflip-executor-contract/blob/ee63f90acfb435f06723e08ce00c2792083f8afb/src/berkeleyRun.ts

Deployed Contract:
https://berkeley.minaexplorer.com/wallet/B62qjb2oGVMGiPad6GKTBh6MqgFJ3ExhkfegBuUiynLoyCSbTfM62vW

**Comment by mitschabaude** [comment]
I get it actually. You're missing the following in your deposit method:
```ts
depositUpdate.requireSignature();
```
therefore, the account update has no authorization on it. The reason it works in tests are that those predefined "test" accounts have their permissions set to not require any authorization.

I think that test behaviour might have been useful at an earlier stage where snarkyjs was less mature, but should be changed now, to not give misleading test results. If you don't mind, I'll change the description of this issue to be about changing permissions on the test accounts

**Comment by mitschabaude** [comment]
> I think AccountUpdate#send should require a signature implicitly, if a signature is required on that account

that makes sense to me. it's just a lot more involved to require the signature depending on the current account permissions (we're in a SNARK, it's all static). also, we have no way of verifying that the prover provides the correct permissions, there's no precondition for permissions (which doesn't pose a security issue here, as far as I can tell). given all that, I'm not sure making this implicit is worth it.

I'll start by properly documenting all those functions like `requireSignature()`

**Comment by cdurling** [comment]
Yeah that all makes sense but to me it is still kind of weird.  `#send` exists primarily as a convenience method right?  To hide `account1.balance.add(x); account2.balance.sub(x);` or whatever is actually going on.  But then the dev 99,999 times out of 100,000 is going to add this `requireSignature` call which feels out place to, say, a solidity programmer.  So I wonder why not just go back and use the more explicit `balanceChange` API which feels more natural in snarkyjs?

I am seeing this in the source code: https://github.com/o1-labs/snarkyjs/blob/fb0946773a46e3aac865b4eb20bca9b6db9e6f9e/src/lib/account_update.ts#L754

```
        // Require signature from the sender accountUpdate
        Authorization.setLazySignature(sender);
```

That makes it sounds like the intention actually was that update requires a signature implicitly.  But then the source code for lazy signature looks more like it's for testing purposes.

**Comment by cdurling** [comment]
I'll leave you to figure it out.  Just leaving my opinions

**Comment by qcomps** [comment]
Yeah that all makes sense but to me it is still kind of weird. `#send` exists primarily as a convenience method right? To hide `account1.balance.add(x); account2.balance.sub(x);` or whatever is actually going on. But then the dev 99,999 times out of 100,000 is going to add this `requireSignature` call which feels out place to, say, a solidity programmer. So I wonder why not just go back and use the more explicit `balanceChange` API which feels more natural in snarkyjs?

I am seeing this in the source code:

[snarkyjs/src/lib/account_update.ts](https://github.com/o1-labs/snarkyjs/blob/fb0946773a46e3aac865b4eb20bca9b6db9e6f9e/src/lib/account_update.ts#L754)

```
        // Require signature from the sender accountUpdate
        Authorization.setLazySignature(sender);
```

That makes it sounds like the intention actually was that update requires a signature implicitly. But then the source code for lazy signature looks more like it's for testing purposes.

I'll leave you to figure it out. Just leaving my opinions.

**Comment by mitschabaude** [comment]
@qcomps the suggestion I get from that is that `accountUpdate.send()` should just add `requireSignature()`, always.
But `SmartContract.send()` shouldn't because many most smart contracts would send with a proof, not a signature.

**Comment by mitschabaude** [comment]
> this requireSignature call which feels out place to, say, a solidity programmer.

Ha! I think that the problem might be that we have the same generic type (AccountUpdate) for both zkApp account updates, and normal user updates. Which are completely different. If we'd create a special type for a "user account update" then we would have methods on it that feel natural, for example because _every_ send from a user needs a signature, so it's added by the method

**Comment by mitschabaude** [comment]
> I am seeing this in the source code: 

This is the token send method, not the one we were talking about, where we decided to require the signature by default. (in part because sending tokens from a zkApp needs a more complicated API anyway)
