### ISSUE TITLE
Permissions error in  merkle_zkapp.ts

### ISSUE THREAD

**Issue by garyrob** [o1-labs/snarkyjs#654]
The Merkle Tree page[1] in the Advanced SnarkyJS section of the docs  links to an example source file, merkle_zkapp.ts[2].

That source file does not compile. It gives the error: 
 TS2339: Property 'permissions' does not exist on type '{ nonce: { get(): UInt32; assertEquals(value: UInt32): void; assertNothing(): void; } & { assertBetween(lower: UInt32, upper: UInt32): void; }; ... 5 more ...; isNew: { ...; }; }'.

[1] https://docs.minaprotocol.com/zkapps/advanced-snarkyjs/merkle-tree
[2] https://github.com/o1-labs/snarkyjs/blob/main/src/examples/zkapps/merkle_tree/merkle_zkapp.ts

**Comment by mitschabaude** [comment]
The source file compiles in the snarkyjs `main` branch, where it's located.
So, the docs link to an example which doesn't work with the released version. This is a temporary issue: We plan to release that new version next Tuesday.
