### ISSUE TITLE
Get rid of `shutdown` by running workers only when needed

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#674]
IS: Workers are started when snarkyjs gets loaded and they keep running throughout the JS process, so that we need to shut them down at the end.

SHOULD: Workers should be started on demand when we start to compile, prove or verify (these are the functions that currently make use of workers). They should be shut down again when those functions terminate.

IMPACT: We can remove `shutdown` which is inconvenient, especially in Jest tests, and is a source of CI failures (forgetting to add `shutdown` to a script means the script will run indefinitely in CI). We also reduce the time to `isReady`, to zero in the case of nodejs (the web version still needs `isReady` since the Wasm bundle can only be loaded asynchronously. We could discuss loading it synchronously with top-level await, to get rid of `isReady` altogether)

**Comment by mitschabaude** [comment]
Note: I'm tagging this with `move-to-js` since it likely involves lifting the current approach to set up workers in node, out of `node_backend.js` which lives in `mina/src/crypto` and is compiled by JSOO, into the main snarkyjs code base.

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @MartinMinkov
