### ISSUE TITLE
Move the `Circuit` class to JS, in part as a wrapper

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#675]
Right now, the `Circuit` class is created in OCaml: https://github.com/MinaProtocol/mina/blob/3faca1de030be8c43212cd3d59dd065164f511e2/src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml#L1593

Subsequently it is heavily monkey-patched in snarkyjs, to add functionality or wrap OCaml functions:
https://github.com/o1-labs/snarkyjs/blob/5c6ce17ba44467ca78e3d2d3e7593c748918f9a4/src/lib/circuit_value.ts#L942-L943

Also, the `Circuit` interface for writing simple (non-Pickles) circuits has its API surface (the class that users interact with) living in OCaml, which makes it hard to maintain and refine that surface. Which is probably why `Circuit`, at this moment, is not integrated with `ZkProgram`, and is neither properly documented nor used very often.

In summary, `Circuit` is a natural place to start the migration of the snarkyjs core (Field, Bool,..) from OCaml to JS.

**How to migrate:**
- Some logic is already basically written in JS, just inside OCaml (which is ugly and unmaintainable), and/or is easy to write in JS on top of lower-level primitives like `Field.mul`, `Field.add`, `Field.assertEquals`. Functions like this should just be moved to JS entirely, using the lower-level building blocks. Examples:
  - `Circuit.if`
  - `Circuit.toFields`
  - `Circuit.assertEqual`
- Some logic can be just replaced by equivalents we already re-built in JS, which will remove [known bugs](https://github.com/o1-labs/snarkyjs/issues/65):
  - `Circuit.inProver`
  - `Circuit.inCheckedComputation`
- Finally, some logic is more involved under the hood, like the circuit-writing interface with functions like `Circuit.generateKeypair` and `Circuit.prove`. Here, the API _surface_ should be moved to JS, but it should still rely on access to a module-like object exposed from OCaml, which has functions like snarky's `constraint_system` and `Keypair.generate` on it.
- Supporting classes like Keypair and VerificationKey should be moved to JS, while also relying on the low-level snarky-wrapping module from OCaml

**Other goals:**

One of the goals of this task is also to feel out what a minimal API surface from JS to the future `snarky-rs` needs to look like. This should inform the [ongoing RFC process for speccing out snarky-rs](https://github.com/o1-labs/snarky/discussions/774) and in particular its interaction with snarkyjs.

**Comment by bkase** [comment]
One important consideration as we start to think about this rewrite is that should be able to support writing circuit snippets in the snarky-rs layer and “seamlessly” using them from JS layer. There’s a lot of ways we could do this and different interpretations of seamless but just wanted to call it out to make sure it’s being considered.

**Comment by mitschabaude** [comment]
That's a good point!

**Comment by mitschabaude** [comment]
## Mini-RFC: Renaming `Circuit` to `Provable`

I propose to split up
* the `Circuit` class for creating proofs, and
* the `Circuit` utility module with functions like `Circuit.if`, `Circuit.witness`, `Circuit.array`
into two different namespaces.

We rename the utility module to 'Provable', so it becomes
* `Provable.if`, `Provable.switch`, `Provable.witness`, `Provable.array`

There should be a deprecation period, but I think long-term we want to get away from 'Circuit' as a term for provable code.

**Comment by nicc** [comment]
IRI: @shimkiv @Trivo25 
Can we do a walk-through of changes during sprint review?
