### ISSUE TITLE
Dummy vk for good DX with proofs disabled on berkeley

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#711]
As of now, in snarkyjs there's a mode `proofsEnabled: false` for testing, where we put dummy proofs on account updates, and don't check the proof before applying it to the local ledger. So far, when using this mode you also didn't have to store a verification key on the account, so you saved the time to compile your contract. The zkapp_command_logic accepted it if there was `authorizationKind: Proof` even without a vk on the account.
However, with [this change](https://github.com/MinaProtocol/mina/pull/12380), that won't be possible - zkapp_command_logic will enforce that there's a vk in the account, matching the vk hash.

So for local testing it'd be nice to have a dummy vk plus hash which is set during compile automatically if you haven't compiled your contract, and `proofsEnabled = false`. I assume such a dummy vk plus hash should be easy to add to the ocaml bindings.

**Comment by Trivo25** [comment]
fixed via #724 closing manually
