### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#727]
* merge berkeley into main (should be quick, because mina was just merged to berkeley)
* sort out the clear mina side branch that corresponds to the new `main` (should be compatible with testnet & snarkyjs and be able to merge to `release/2.0.0`
* add missing stuff to changelog
* bump version

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @mitschabaude 
(Gregor, if you end up taking this work on then let me know and we'll find someone else)
