### ISSUE TITLE
Prepare for zkIgnite architecture workshop

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#728]
Goal is to come up with a specific zkApp idea that we can talk through how to build this with our existing feature set for zkApps. No code needed, this isn't a tutorial, it's a discussion of our feature set and how it can be used to solve a business use case. Minimal slides is okay. , but we may want an architecture diagram highlighting features. 

Output:
1. Idea to discuss
2. Identify DRI to present, and 1-2 additional devs to attend to support audience Q&A. 

CC @nicc

**Comment by jasongitmail** [comment]
auction?

**Comment by jasongitmail** [comment]
Accepted idea: voting with access gated by an email oracle

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @Trivo25 and @jasongitmail

**Comment by mitschabaude** [comment]
Done! :D
