### ISSUE TITLE
Discussion: Supporting richer filtering options related to fetching events/actions

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/snarkyjs#762]
## Description

Related too https://github.com/o1-labs/snarkyjs/pull/749

Should we change the `fetchEvents` and `fetchActions` method signatures to take in more filtering options? I propose we add support for filtering by block heights (with `to` and `from` or `start` and `end` variables). 

## Impact

By allowing filtering by block height, users of `fetchEvent` or `fetchAction` will get a more precise data set of events/actions when they are being fetched. It's unnecessary to return _all_ events/actions data unless the user wants to do that (the default behaviour is if they do not pass in any filtering options). This will also put less burden on the GraphQL server itself since it has to process fewer rows if filtering is being added.

**Comment by mitschabaude** [comment]
+1 for filtering by block height, and we don't need filtering by slot then IMO

**Comment by Trivo25** [comment]
Definitely! I wonder if it would be useful to also filter by event type

**Comment by MartinMinkov** [comment]
Sweet! I'll close this out since we have an agreement on the API now. :D
