### ISSUE TITLE
Implement hashing to curve

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#772]
Primitive needed for zk nullifiers & useful to have in general

IETF draft: https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-16.html
Twitter discussion: https://twitter.com/hdevalence/status/1630463319336435714

**Comment by Trivo25** [comment]
convenient reference for pasta curves https://github.com/zcash/pasta_curves/blob/main/src/hashtocurve.rs#L10
