### ISSUE TITLE
Can we make universality transitive in SnarkyJS/pickles/kimchi?

### ISSUE THREAD

**Issue by bkase** [o1-labs/snarkyjs#776]
Mina’s L1 supports universality in the zkapp cpu his kimchi/pickles . Can we tap into universality at the programmable module layer? Can we define a recursive circuit in snarkyjs that can verify proofs of older versions of itself?
This would allow upgrades of the zk circuit during recursive aggregation without having to settle to the L1 in between.

Why:
Having this feature would make it more practical to build cross-communicating zkAppChain rollups + allow SnarkyJS/Kimchi to be directly used as the core for other recursively composable platforms like they can on the Mina L1 (L2s, L3s, L4s, etc that settle on Mina for example)

**Comment by mimoo** [comment]
we could easily do this now, but depending on the changes in the proof system it might become less and less "easy" and more and more of a nightmare. Basically, we will either have to fork the verifier circuit every time we do a breaking change in the proof system, or if we can, make the verifier circuit more general depending on configuration.

**Comment by bkase** [comment]
And this is already tracked here! https://github.com/o1-labs/snarkyjs/issues/776
