### ISSUE TITLE
mini RFC: fallback URLs for archive node API and mina API

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#781]
I.e. if the first is non-responsive after a certain time period, send HTTP request to a 2nd URL.

**Comment by mitschabaude** [comment]
## Mini-RFC: Fallback URLs

### API

We keep the current API, but the `mina` and `archive` endpoints can be either a string or a _list of strings_:

```ts
Mina.Network({
  mina: ["https://berkeley.minascan.io/graphql", "https://berkeley.minaexplorer.com/graphql"],
  archive: ["...", "..."]
});
```

### Behaviour

We fetch from all endpoints simultaneously and use the first result that arrives, using `Promise.race`

**Comment by MartinMinkov** [comment]
Is it worth supporting the Mina node's GraphQL API for the `mina` property? That way, if any services go down, someone always has the capability of spinning up their node and using a node as a final fallback.

**Comment by mitschabaude** [comment]
> Is it worth supporting the Mina node's GraphQL API for the `mina` property? That way, if any services go down, someone always has the capability of spinning up their node and using a node as a final fallback.

Definitely! Mina node graphql spec is what we always developed against, so would be wrong to not support it for some minor reason

**Comment by jasongitmail** [comment]
> either a string or a list of strings
+1

> Behaviour
> 
> We fetch from all endpoints simultaneously and use the first result that arrives, using Promise.race

Seems good in the short term because of the ease of implementation. Longer term, we probably don't want to enable devs to fetch from unlimited endpoints simultaneously, as an example, because of the unreasonable burden it'd put on API providers if they list every one they are aware of or something similarly silly. So we might want to discuss waterfalling to fallback URLs after a timeout or throttling. But this is good for now.

**Comment by MartinMinkov** [comment]
> Definitely! Mina node graphql spec is what we always developed against, so would be wrong to not support it for some minor reason

I just mention this cause I'm not sure if the Mina node's GraphQL API matches exactly of what the other API providers are, if it is then easy work :D But I thought there could be a small chance of changing some of the queries.

**Comment by garethtdavies** [comment]
> I just mention this cause I'm not sure if the Mina node's GraphQL API matches exactly of what the other API providers are, if it is then easy work :D But I thought there could be a small chance of changing some of the queries.

It'll be the same, it's just a reverse proxy in front of the daemon GraphQL API with the addition of removing some sensitive queries/mutations. Those left should behave exactly the same way.
