### ISSUE TITLE
getAccount() fails to find Account: Could not find account for public key...

### ISSUE THREAD

**Issue by gordonfreemanfree** [o1-labs/snarkyjs#797]
When using getAccount() with a token id other than the default (Mina) it throws an error:

 let newAccountInfo = Mina.getAccount(zkAppAddress, zkApp.token.id)

_getAccount: Could not find account for public key B62...GPmp7 with the tokenId yG...Umxi_

It looks like _getAccount_ is making a GraphQL query with an undefined public key and the default token id.
This can be found in the logs of GraphQL proxy:

"message": "Argument publicKey of type PublicKey expected on field account, found \"undefined\"."
_{
  account(publicKey: "undefined", token: "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf") {
    publicKey
    token
    nonce
    balance {
      total
    }_
    
  
The issue is also discussed here:
 https://discord.com/channels/484437221055922177/1070807617586352260/1085598944593203304
 
 snarkyJS: 0.9.2
 (plz add ITN-zkApps-E2E-testing label)

**Comment by Trivo25** [comment]
https://discord.com/channels/484437221055922177/1085598944593203304/1085689371971293256

**Comment by Trivo25** [comment]
@gordonfreemanfree does the issue continue to persists with SnarkyJS version 0.9.3?
