### ISSUE TITLE
Add analyzeMethods() to ZkProgram

### ISSUE THREAD

**Issue by maht0rz** [o1-labs/snarkyjs#827]
Since i began using ZkProgram i have been trying to be cautious about not going over the 2^16 circuit size limit. The only way i knew how to figure out my circuit size, was to use `SmartContract.analyzeMethods()`. I could not find the same for ZkProgram, so i've decided to follow how it is done for SmartContract.

For my own purposes, i've tried adding the following to the [`ZkProgram`](https://github.com/o1-labs/snarkyjs/blob/main/src/lib/proof_system.ts#L270):

```typescript
function analyzeMethods() {
  return methodIntfs.map((methodEntry, i) =>
    analyzeMethod(publicInputType, methodEntry, methodFunctions[i])
  );
}

return Object.assign(
  selfTag,
  { compile, verify, digest, publicInputType, analyzeMethods },
  provers
);
```

^ the code above might not be 100% correct, but when i injected something along these lines into my built snarkyjs dependency, i was able to inspect the amount of 'rows' in my ZkProgram.

Does this approach make sense? If yes, i can open a PR.

**Comment by mitschabaude** [comment]
Yes this makes sense and a PR would be highly appreciated!

**Comment by mitschabaude** [comment]
done with the linked PR
