### ISSUE TITLE
Create list of high-value error messages to improve

### ISSUE THREAD

**Issue by nicc** [o1-labs/snarkyjs#849]
We are intent on improving our error messages in general. There are some initivates that unblock this. In preparation for these improvement, we'd like a list of the most impactful error messages to focus on first.

Consider all errors (protocol, crypto, snarkyjs). Timeboxed to an estimate of 5. No more than 20 items.

Preemptive candidates:
- Out of memory
- Circuit size

Resources for when we are ready to improve the error messages:
- https://www.nngroup.com/articles/error-message-guidelines
- https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4
- https://bootcamp.uxdesign.cc/7-steps-to-design-error-messages-49e509f03d18

**Comment by barriebyron** [comment]
@ymekuria  shared https://github.com/MinaProtocol/docs/blob/main/pages/en/node-operators/transaction-failures.mdx that has been floating around, not published in the docs as of April 11, 2023

**Comment by nicc** [comment]
Another candidate:

`Account_action_state_precondition_unsatisfied` error during `Reducer.reduce` usually when you reduce the wrong set of actions (because you hash the wrong actions and the target hash doesn't match the committed on-chain hash anymore)

**Comment by nicc** [comment]
IRI: @nicc

**Comment by mitschabaude** [comment]
Here's a truly bad one: https://github.com/o1-labs/snarkyjs/issues/808
If you forget to add a proof even though you set `authorizationKind` to "proof", the error is just:
```
Assert_failure src/lib/transaction_logic/zkapp_command_logic.ml:1266:17
```
(thrown from inside the transaction logic, called by LocalBlockchain)

**Comment by mitschabaude** [comment]
Basically, every error thrown from inside snarky is bad, because of the **long and noisy stack trace**. @mrmr1993 had some good ideas to address this.

Here's an example for when a constraint fails inside the prover (for example, during `tx.prove()`):

![image](https://user-images.githubusercontent.com/20989968/231503585-95f25e03-78af-4b4d-b6c0-dce33c7e9a11.png)


[constraint-unsatisfied.txt](https://github.com/o1-labs/snarkyjs/files/11212973/constraint-unsatisfied.txt)

**Comment by Kirol54** [comment]
I'm assuming it's coming from graphql as not undefined but it's not really helpful error message 

<img width="767" alt="image" src="https://user-images.githubusercontent.com/36684975/231592134-06c188e3-338a-4894-a461-5b309da8c776.png">

**Comment by rpanic** [comment]
I guess `Can't evaluate prover code outside an as_prover block` can be improved

**Comment by mitschabaude** [comment]
'Permutation failed' for when you create a different circuit every time because you use a constant instead of a variable

**Comment by nicc** [comment]
@nicc to review / create new issues

**Comment by shimkiv** [comment]
Another messages for consideration:

- https://github.com/o1-labs/e2e-tests/issues/56
- https://github.com/o1-labs/snarkyjs/issues/425
- https://github.com/o1-labs/snarkyjs/issues/478
- https://github.com/o1-labs/snarkyjs/issues/601
- https://github.com/o1-labs/snarkyjs/issues/743
- https://github.com/o1-labs/snarkyjs/issues/782
- https://github.com/o1-labs/snarkyjs/issues/841

cc @nicc

**Comment by nicc** [comment]
All improvements identified here have been reflected as new issues with the `error-messages` label. Closing this issue. Thank you, everyone!
