### ISSUE TITLE
Mina `transaction` and `fundNewAccount` deprecation of private key arg

### ISSUE THREAD

**Issue by Isaac-DeFrain** [o1-labs/snarkyjs#862]
The [deprecated private key arg](https://github.com/o1-labs/snarkyjs/issues/635) of these methods is reflected in the VSCode UI but not in zkapp-cli 0.7.5. You can confirm with any of the tests in [this code](https://github.com/garethtdavies/zkAppPool/blob/main/oracle/src/DelegationOracleVerifier.test.ts).
Reading the 635 issue, it seems like this will be supported in 0.8.0.

**Comment by mitschabaude** [comment]
Hey @Isaac-DeFrain! I don't quite understand what behavior you find missing. Do you mean the zkapp-cli should warn about deprecated arguments in its console output?

**Comment by Isaac-DeFrain** [comment]
Sorry and thanks for the quick reply @mitschabaude! The VSCode UI informs a dev that passing `PrivateKey`s to these methods is deprecated. However, when you make that change in your code, all the corresponding tests fail.

**Comment by mitschabaude** [comment]
Gotcha. The public key fee payer argument should work, what was the error you got? Something about missing private key? You have to pass the private key to tx.sign()

**Comment by Isaac-DeFrain** [comment]
You're right! It works perfectly, just didn't realize that I need to pass both the zkapp and deployer private keys, but that did the trick. Thanks!
