### ISSUE TITLE
Tutorial 1 expected assert_equal output is incorrectly output as hexadecimal

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/snarkyjs#865]
Run [Tutorial 1](https://docs.minaprotocol.com/zkapps/tutorials/hello-world#write-the-zkapp-smart-contract) 

on Mina zkApp CLI 0.6.4 and SnarkyJS 0.8.0.

For this step:

> Now let's try adding a transaction that should fail - updating the state to 75. Now that num is in state 9, updating should only be possible with 81.

The expected output at this part of the tutorial for running:
`npm run build && node build/src/main.js`
is
```
SnarkyJS loaded
state after init: 3
state after txn1: 9
assert_equal: 75 != 81
state after txn2: 9
Shutting down
```

But... surprise! when I run the command, the output incorrectly includes hexadecimal values:

```
➜  01-hello-world git:(main) ✗ npm run build && node build/src/main.js

> 01-hello-world@0.1.0 build
> tsc

SnarkyJS loaded
state after init: 3
state after txn1: 9
Shutting down
➜  01-hello-world git:(main) ✗ npm run build && node build/src/main.js

> 01-hello-world@0.1.0 build
> tsc

SnarkyJS loaded
state after init: 3
state after txn1: 9
assert_equal: 0x000000000000000000000000000000000000000000000000000000000000004B != 0x0000000000000000000000000000000000000000000000000000000000000051
state after txn2: 9
Shutting down
➜  01-hello-world git:(main)
```

**Comment by mitschabaude** [comment]
heads up: [this PR](https://github.com/o1-labs/snarkyjs/pull/902) will change the output to
```
Field.assertEquals(): 75 != 81
```
do you agree that output is better @barriebyron?
