### ISSUE TITLE
docs use consistent spelling of product names, esp. SNARK workers

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/snarkyjs#877]
Docs build trust when we are consistent and accurate.
For example, `SNARK workers` have various spellings throughout the docs

Make updates throughout docs to follow the https://github.com/o1-labs/docs2/wiki/Word-list to update the docs so we use consistent terminology

**Comment by mitschabaude** [comment]
can we move this issue to the docs repo?

**Comment by barriebyron** [comment]
> 

yes of course, is this move something I have the power to learn and do?

**Comment by mitschabaude** [comment]
> > 
> 
> yes of course, is this move something I have the power to learn and do?

I think there's no way to do it except recreate it in the other repo!

**Comment by barriebyron** [comment]
I inadvertently created this docs PR in the codebase repository, closing here

**Comment by mitschabaude** [comment]
Fun fact: since I wrote the comment above I learned that GitHub allows you to transfer issues! It's a small link on the side/bottom, "Transfer issue"
