### ISSUE TITLE
Max `UInt64` returns an error

### ISSUE THREAD

**Issue by Isaac-DeFrain** [o1-labs/snarkyjs#891]
Multiple ways to get the max value for `UInt64`s return an error.
1. `UInt64.MAXINT()`
![Screenshot 2023-05-04 204211](https://user-images.githubusercontent.com/42081488/236365048-c3411b7a-da12-4cbc-86df-a1d4a101a845.png)
2. `UInt64.from(18_446_744_073_709_551_615)`
![Screenshot 2023-05-04 203852](https://user-images.githubusercontent.com/42081488/236365183-28954509-5945-4d5c-af4e-229f93ddb6e7.png)

**Comment by mitschabaude** [comment]
I can't reproduce the error with `UInt64.MAXINT()`:

![image](https://user-images.githubusercontent.com/20989968/236386037-9de1f373-ad1f-4485-b545-dc592b28bd53.png)

The second error I can explain: the JS `number` type can't represent 2^64-1 exactly as an integer -- as you see, it gets rounded up, which makes it too large for a UInt64. The solution is to use `bigint` for large numbers:

![image](https://user-images.githubusercontent.com/20989968/236386473-f0e6fa1c-a03a-469d-a1ba-70be81e9d3de.png)

**Comment by Isaac-DeFrain** [comment]
1. Yeah I have no idea... Now I can't even reproduce the error. It's for the best!
2. That makes sense.
