### ISSUE TITLE
Pushing to array causes heap OOM error

### ISSUE THREAD

**Issue by Isaac-DeFrain** [o1-labs/snarkyjs#903]
The contract method
```typescript
@method update() {
  let num = this.num.get();
  this.num.assertEquals(num);

  let arr = [UInt64.from(1), UInt64.from(2), UInt64.from(3)];
  for (let i = 0; i < arr.length; i++) {
    Circuit.if (
      num.lessThan(arr[i]),
      UInt64.from(arr.push(num)),
      UInt64.from(0)
    );
  }
}
```

The error message
```
<--- Last few GCs --->

[3583:0x5735a60]   295530 ms: Scavenge (reduce) 2044.6 (2081.2) -> 2043.6 (2081.5) MB, 2.9 / 0.0 ms  (average mu = 0.157, current mu = 0.120) allocation failure; 
[3583:0x5735a60]   297409 ms: Mark-sweep (reduce) 2044.6 (2081.5) -> 2042.8 (2081.5) MB, 1872.1 / 0.0 ms  (average mu = 0.109, current mu = 0.060) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb652d0 node::Abort() [node]
 2: 0xa761b5 node::FatalError(char const*, char const*) [node]
 3: 0xd55b6e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd55ee7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf32f15  [node]
 6: 0xf33e18 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xf44323  [node]
 8: 0xf45198 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf1fafe v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xf20ec7 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
11: 0xf0209a v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
12: 0x12c548f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
13: 0x16f6939  [node]
Aborted
```

**Comment by mitschabaude** [comment]
isn't this just an infinite loop? :D you're iterating until `arr.length` which is never reached because you're also pushing to that array?

**Comment by Isaac-DeFrain** [comment]
It appears that it is, but it shouldn't be.

Is `arr.length` not evaluated only once, upon entering the for loop?

Even if that's not the case, this should only add at most `arr.length` elements (in this case 3) to `arr` because of the strict condition `num.lessThan(arr[i])`. Even if it is possible that `i = 3`, then `arr[3] === num` making `num.lessThan(arr[3]) === Bool(false)` so we don't push another element. Similarly for 4 and 5.

**Comment by Isaac-DeFrain** [comment]
You're right about `arr.length`, it changes during execution!
Is is wrong to expect similar semantics to this?
![image](https://user-images.githubusercontent.com/42081488/236948889-c535c178-7b67-4de6-94dc-969857ccfe40.png)

**Comment by mitschabaude** [comment]
Ok sorry I didn't catch the details of the example -- that this would stop pushing to the array and finish, if one of the `if` branches wouldn't be executed.

>  Is is wrong to expect similar semantics to this?

Yes, those semantics can't be expected, because you're writing normal JS that is executed as JS, with no compilation or anything like it going on. And `Circuit.if` is not a builtin JS control flow operator, it's a normal function call. When you call a function, all of its arguments are evaluated before calling the function. So, in your original example, you're performing `arr.push(...)` in every loop iteration, while in the last example, it's behind an actual `if` statement so it's not always executed.

**Comment by Isaac-DeFrain** [comment]
Gotcha. In that case, is it possible to add a premature error about the infinite loop? Otherwise, you just wait a few minutes for the heap to be exhausted which is not ideal. Maybe this is a good task for a static analysis tool 😉

**Comment by trevorbernard** [comment]
That difference is certainly confusing and will likely be the source of hard to catch bugs. One way to match the JavaScripts `if` semantics could be passing in a function references for both paths of the branch but I don't know if that's any better. Ideally JavaScript would have a macro system for syntactic sugar but alas it doesn't. I agree with Isaac in that this could be part of a static code analysis tool or at the very least, have it documented somewhere as a warning.

**Comment by mitschabaude** [comment]
I addressed this for now by including a warning in the doccomments of `Circuit.if` in this PR: https://github.com/o1-labs/snarkyjs/pull/889
