### ISSUE TITLE
String Implementation

### ISSUE THREAD

**Issue by qcomps** [o1-labs/snarkyjs#92]
It would be convenient to have strings native in snapps.  Snapp state could point to a URL with more information about the snapp itself.  A username could be included in a circuit, etc...

I have an implementation I have been working on, but I'm wondering what the spec should be if it were to become a PR into the library.

The way my version works is I defined a `UInt8` CircuitValue and implemented a `StringCircuitValue` as an array of UInt8.  The primary interface with a snapp is in the `fromBits` and `toBits` functions which allow a user to initialize a field as bits, and convert back to a string.  e.g.

```
  it('can serialize and deserialize from Field', () => {
    const input = 'Input String 123'
    const ztring = new StringCircuitValue(input);
    const field = Field.ofBits(ztring.toBits());
    expect(StringCircuitValue.fromBits(ztring.toBits()).toString()).to.eq(input);
    expect(StringCircuitValue.fromBits(field.toBits()).toString().replace(/\0/g, '')).to.eq(input);
  });
```

I have not thought out edge cases like trying to pack in more than 256 bits of data, nor thought about performance or security. Just worked on the happy path until now.  If there's interest in merging something like this into snarky, I would be happy to clean it up.  Ideally there would be a spec of what o1 thinks a string ought to behave like, but if not, I'd like to get some feedback regarding concerns or holes I may not have considered.  If this implementation doesn't work, then maybe it will spark some discussion to find one that does.

To view my implementation, see these relevant files:

String.ts: https://github.com/qcomps/cachebox/blob/2369e41e55d3b78285cad2cfa9a2d0ef545d4f41/src/lib/snarkyUtils/String.ts

UInt8.ts (other than the relevant parts, this is a lazy port of UInt64, which may not actually work for math): https://github.com/qcomps/cachebox/blob/2369e41e55d3b78285cad2cfa9a2d0ef545d4f41/src/lib/snarkyUtils/UInt8.ts

String.test.ts: https://github.com/qcomps/cachebox/blob/2369e41e55d3b78285cad2cfa9a2d0ef545d4f41/test/snarkyUtils/String.test.ts

UInt8.test.ts: https://github.com/qcomps/cachebox/blob/2369e41e55d3b78285cad2cfa9a2d0ef545d4f41/test/snarkyUtils/UInt8.test.ts

**Comment by mitschabaude** [comment]
Cool! UInt8 looks good to me, String not yet because it doesn't have any @prop, so it's an CircuitValue representing 0 Fields in the Circuit. You'll need an @arrayProp and have a fixed max length for the String. Also, I'd prefer an implementation that avoids toBits / fromBits because that is super expensive. Better to make to make a primary interface based on Uint8 (which can be mostly thought of as individual characters)

Will take a deeper look tomorrow.

**Comment by qcomps** [comment]
@mitschabaude thanks for taking a look!

I went with from/to bits because I wanted to be able to read a string off of state.  I went back to your sudoku example to see how you implemented your storage, and to convert to a field, you hashed the circuit value into something that could not be read by anyone else.  A 9x9 matrix is too big to store in 32 bytes however you look at it, but 32 UInt8s should be able to fit, so I was thinking what I could change so that 1 string <=> 1 field.

Could I do the same with `Field.ofFields`?  Or how else would "a primary interface based on Uint8" work?

**Comment by mitschabaude** [comment]
@qcomps Ok, I understand. You want to compress a string to 1 Field of on-chain state and be able to read it back to an array of UInt8s.

First, I have to point out that 1 Field can't really hold 32 bytes of on-chain storage -- it can hold 254 bits, so only 31 full bytes.

I'd do it like this:

To compress a StringCircuitValue to a Field, you just compute a number in base-8 representation. In pseudo-code:
`x = s[0] + 8 * s[1] + ... + 8^30 * s[30];`
Real code might be this:
```js
function stringToField(circuitString) {
  let s = circuitString.value;
  let field = Field(0);
  for (let i = 0, b = 1; i < 31; i++, b*=8) {
    field = field.add(s[i]).mul(b);
  }
  return field;
}
```

To go the other direction -- string from a field -- you just compute the string outside the circuit, bring it into to tha circuit with Circuit.witness (this is basically "pulling a witness out of your hat"). Then you use your reverse direction and an assertion to constrain the outside-circuit computation such that it has to do the right thing:

```js
function fieldToString(field) {
  let circuitString = Circuit.witness(StringCircuitValue, () => {
    computeStringOutsideCircuit(field); // write this function yourself, e.g. with field.toString()
  });
  // constrain it to be the correct string:
  let field2 = stringToField(circuitString);
  field.assertEquals(field2);
  
  return circuitString;
}
```

**Comment by mitschabaude** [comment]
EDIT: I mixed up `8` and `2^8` yesterday, corrected the code above now

**Comment by mitschabaude** [comment]
Also, I'm not really sure about how efficient this is, it depends on the assumption that 1 UInt8 range check is more efficient than a naive range check with 16 constraints. I'll try to look what we're using here. I think I figured out a way to do either UInt8 or UInt16 with a single constraint, at the cost of introducing a look-up table... maybe we have something like that already.

**Comment by qcomps** [comment]
@mitschabaude I'm trying to wrap my head around this...

It still seems like a one-way function right?  We might as well hash the UInt8s together, or am I missing something?  If we know what the string is, then we can use any one-way function to prove that we know what the output of the function is for the string.

field<sub>i</sub> = (field<sub>i+1</sub> + s<sub>i</sub>) * b<sub>i</sub>

This equation in reverse has 2 unknowns.  We know field<sub>i+1</sub> and b, but we don't know field<sub>i</sub> or s<sub>i</sub>.


So am I interpreting that correctly that you wouldn't be able to serialized back from a big int to a UInt8[]? Is `Field.ofBits` only slow in the context of a circuit generating an actual proof?  How bad is it?  I'm wondering if hashing a string and "pulling a witness out of a hat" would be appropriate almost all the time, but if reading a string raw directly off the state is required in a certain case, then we would have `StringCV.fromBits()` as an option?

For a use case, let's say the most recent person to earn access to a puzzle gets to sign their name to some state called `lastWinner` and we want to let them use letters, and we want anyone else to be able to read that state without already knowing it.  In this case we would likely never compute a proof where the value of this state is checked as an input, but anyone who attempts the snapp, from any client which may be running the source code, will be able to see what the last winner has to say to them.

**Comment by qcomps** [comment]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/36939461/153990882-1071c131-b600-44d2-8a5e-4f3a991d3626.png">

It's possible that I'm missing some property of 2^8 that I'm not understanding.

**Comment by mitschabaude** [comment]
No sorry @qcomps you misunderstood me. This is not a one-way function, it is actually the same as field.toBits / fromBits, just splitting the field into bytes (8-bit vectors) instead of single bits. The intention *was* that you can get the byte array back from the field. You get the byte array back like that:
1.) Test the field's first 8 bits (bit 0 to 7) => store as first element of byte array
2.) Test the field's bits 8 to 15 => store as first element of byte array
3.) and so on

It's more efficient than fromBits because there are only 31 bytes, but 254 bits, and each of those bits will need a constraint in your circuit.

Feel free to use your version with fromBits / toBits for now! I'll add something like outlined above to snarkyjs eventually

**Comment by mitschabaude** [comment]
@qcomps Try to think of it with the base 10 instead of 256. I can map a number to / from an array of digits like that:

toDigits: 21316 => [2, 1, 3, 1, 6]

fromDigits: let x = 2 + 1*10^1 + 3*10^2 + 1*10^3 + 6*10^4

I did the same as fromDigits but with base 256. A byte is a number between 0 and 255 so this works.

**Comment by qcomps** [comment]
Synced with @mitschabaude more offline, and came up with this more efficient to/from Field interface:

```
  toField(): Field {
    const values = this.value.map(x => x.value); // this.value is a UInt8[] circuit value
    let field = Field.zero;

    for (let i = 0, b = Field.one; i < Math.min(values.length, 31); i++, b = b.mul(256)) {
      field = field.add(values[i].mul(b));
    }
    return field;
  }

  static fromField(field: Field): StringCircuitValue {
    const values: UInt8[] = [];

    field.toConstant().value[1].forEach((v) => {
      values.push(UInt8.fromNumber(v))
    }); // using the fact that a field constant is represented as a typescript UInt8[]

    const stringVal = new StringCircuitValue('');
    stringVal.value = values;
    return stringVal;
  }
  ```
  
  Passes this test:
  
  ```
  describe('fromField', () => {
  it('can serialize and deserialize from Field', () => {
    const input = 'Input String 123'
    const ztring = new StringCircuitValue(input);
    const stringValue = StringCircuitValue.fromField(ztring.toField());
    expect(stringValue.toString().replace(/\0/g, '')).to.eq(input);
  });
});
```

**Comment by mitschabaude** [comment]
Nice! Just noting that if you want to use your `fromField` in a circuit, you still have to do the dance I described above with `Circuit.witness` and then checking that the UInt8[] does in fact compress back to the original field when passed to `toField`

**Comment by mitschabaude** [comment]
Would still be nice to have something like this in snarkyjs! PR welcome

**Comment by qcomps** [comment]
So it sounds like the fundamental issue to solve here is that we want to be able to prove things like substring, case-insensitive equality, and other things related to the properties of characters and their order within a string.  The current de facto string equality function uses bijective encoding, but we are after additional properties that are commonly relied on by devs than simply equality.

I will pick this back up and try to get some simple functionality built out!

**Comment by mitschabaude** [comment]
Yeah, basically we want `array of UInt8` with some nice helper methods
