### ISSUE TITLE
Make an example zk app where SnarkyJS generates deploy/user transactions

### ISSUE THREAD

**Issue by bkase** [o1-labs/snarkyjs#97]
For testing purposes

Ensure that all the data fields of the transaction are filled out properly

Make sure that SnarkyJS is capable of (optionally) signing itself AND that we could optionally hand it to Mina Signer

**Comment by mitschabaude** [comment]
Mostly done, TODO for today is adding the signing capability to snarkyjs
Not sure if in scope, but another TODO is getting the zkapp to be accepted by the internal mock mina interface as a sanity check

**Comment by mitschabaude** [comment]
I consider this closed with https://github.com/MinaProtocol/mina/pull/10674 merged
