### ISSUE TITLE
Block crypto PRs on all tests

### ISSUE THREAD

**Issue by nicc** [o1-labs/snarkyjs#973]
Block crypto PRs on both sets of tests that were split apart in issue #971. i.e. crypto PRs should always require a fully passing test suite.

**Comment by mitschabaude** [comment]
following the RFC, I think the minimal snarkyjs test suggested there might be enough for crypto tests, and we can call this done with https://github.com/MinaProtocol/mina/pull/13430

**Comment by mitschabaude** [comment]
I think this can be closed now per the comment above
